// frontend-angular/src/app/disabled-user/disabled-user.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-disabled-user',
  templateUrl: './disabled-user.component.html',
  styleUrls: ['./disabled-user.component.scss']
})
export class DisabledUserComponent {
}

<p>This user account is currently disabled. Please contact the system administrator to unblock this account.</p>

// frontend-react/src/auth/DisabledUser.jsx
import React from 'react';
import { Typography, makeStyles } from '@material-ui/core';

const useStyles = makeStyles(() => ({
  verticalCenterContents: {
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  horizontalCenterContents: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  }
}));

function DisabledUser() {
  const classes = useStyles();
  return (
    <div className={classes.verticalCenterContents}>
      <div className={classes.horizontalCenterContents}>
        <Typography variant="body1">This user account is currently disabled. Please contact the system administrator to unblock this account.</Typography>
      </div>
    </div>
  );
}

export default DisabledUser
